### ISSUE TITLE
No handlers could be found for logger "oauth2client.contrib.multistore_file"

### ISSUE THREAD

**Issue by jcomfort4** [GoogleCloudPlatform/cloudml-samples#88] opened 2017-10-07 18:12 UTC
For problems running the sample code please provide the following information.

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac 
- **TensorFlow version (use command below)**: 1.2.1
- **Python version**: 2.7.13
- **Exact command to reproduce**: See below
- **Tensorflow Transform environment (if applicable, see below)**: 0.1.10

### Describe the problem
I am trying to run the reddit_tft preprocess.py file and I got the following error:

```
No handlers could be found for logger "oauth2client.contrib.multistore_file"
2017-10-07 14:04:08.637282: F tensorflow/core/platform/cloud/http_request.cc:334] Check failed: that->post_body_read_ <= that->post_body_buffer_.size() 
Abort trap: 6
```

I downloaded the most recent cloudml-samples, unzipped it and switched to the reddit_tft folder. Then I typed in the command instructed on the readme:

```
python preprocess.py --training_data fh-bigquery.reddit_comments.2015_12 \
                     --eval_data fh-bigquery.reddit_comments.2016_01 \
                     --predict_data fh-bigquery.reddit_comments.2016_02 \
                     --output_dir "${PREPROCESS_OUTPUT}" \
                     --project_id "${PROJECT}" \
                     --cloud
```

I recognize that the requirements technically say tensorflow 1.2.0, but I am running this on the cloud and the error does not seem to have anything to do with tensorflow so I don't think the fact that I have 1.2.1 should have an effect.

Any ideas why this sample is not working for me?

**Comment by puneith** [comment] 2017-11-02 13:52
I think I know what the problem is. Let me look into this and get back to you.

**Comment by puneith** [comment] 2018-02-02 15:48
@jcomfort4 Can you please look at the [PR](https://github.com/GoogleCloudPlatform/cloudml-samples/pull/157) and confirm it works for you.

**Comment by puneith** [comment] 2018-06-16 21:55
@jcomfort4 ping on this.

**Comment by puneith** [comment] 2018-10-13 04:48
@jcomfort4 the PR above is merged and works. Closing this issue.

**Closed by puneith** 2018-10-13 04:48 UTC
Labels: bug
