### ISSUE TITLE
ImportError from movielens example

### ISSUE THREAD

**Issue by IvanWeiZ** [GoogleCloudPlatform/cloudml-samples#245] opened 2018-09-12 18:45 UTC
I tried to run the movielens example and during the training stage I got following error.

```
created:  1536771676.252262   
  exc_info:  "None"   
  levelname:  "ERROR"   
  lineno:  55   
  message:  "Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/pip-install-tUm0cc/fastavro/setup.py", line 104, in <module>
    setup_requires=setup_requires
  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 262, in __init__
    self.fetch_build_eggs(attrs['setup_requires'])
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 287, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 631, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 874, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 886, in obtain
    return installer(requirement)
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 338, in fetch_build_egg
    return cmd.easy_install(req)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 636, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 666, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 856, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1078, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1063, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 68, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 114, in run
    return func()
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 67, in runner
    _execfile(setup_script, ns)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 43, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-rN03YB/setuptools-40.2.0/setup.py", line 194, in <module>
  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 266, in __init__
    _Distribution.__init__(self,attrs)
  File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 301, in finalize_options
    ep.load()(self, ep.name, value)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2195, in load
    raise ImportError("%r has no %r attribute" % (entry, attr))
ImportError: <module 'setuptools.dist' from '/usr/lib/python2.7/dist-packages/setuptools/dist.pyc'> has no 'check_specifier' attribute
"   
  pathname:  "/var/sitecustomize/sitecustomize.py"   
 }
```

**Comment by gogasca** [comment] 2018-09-14 16:47
Hi @IvanWeiZ 
Thanks for reporting this issue, are you using a virtual environment as described in the [pre-requisites](https://cloud.google.com/ml-engine/docs/tensorflow/getting-started-training-prediction) section?
I tried to go through the tutorial and was not able to reproduce the issue.
If you already using a virtual environment, can you share the following:

- OS version
- python -V
- pip freeze

**Comment by IvanWeiZ** [comment] 2018-09-14 16:51
Hello @gogasca,

I submitted the job to Cloud ML using the default runtime environment.  I did not test the code locally. After I chose a newer version of the runtime environment like 1.4, I got other errors like 
File "/root/.local/lib/python2.7/site-packages/tensorflow_transform/tf_metadata/v1_json/schema_io_v1_json.py", line 54, in read raise IOError("v1 Schema file does not exist at: %s" % path) IOError: v1 Schema file does not exist at: movielens_20180912_111837/raw_metadata/v1-json/schema

Thanks,

**Comment by gogasca** [comment] 2019-05-21 05:55
We have deprecated this sample, I will go ahead and close this PR

**Closed by gogasca** 2019-05-21 05:55 UTC
Labels: type: bug
