### ISSUE TITLE
F tensorflow/core/platform/cloud/http_request.cc:334] Check failed: that->post_body_read_ <= that->post_body_buffer_.size() 

### ISSUE THREAD

**Issue by corey219** [GoogleCloudPlatform/cloudml-samples#55] opened 2017-06-23 23:32 UTC
Hi,

While running the reddit sample I am getting the following error:

```
python preprocess.py --training_data fh-bigquery.reddit_comments.2015_12 \
>                      --eval_data fh-bigquery.reddit_comments.2016_01 \
>                      --predict_data fh-bigquery.reddit_comments.2016_02 \
>                      --output_dir $GCS_PATH/preproc \
>                      --project_id $PROJECT \
>                      --cloud
No handlers could be found for logger "oauth2client.contrib.multistore_file"
2017-06-23 12:41:21.869701: F tensorflow/core/platform/cloud/http_request.cc:334] Check failed: that->post_body_read_ <= that->post_body_buffer_.size() 
Abort trap: 6
```

Any idea why I am getting this error?

Thanks

**Comment by dobbysock1002** [comment] 2017-06-24 04:47
I was getting this same issue. It seems like it was tied to tensorflow==1.2.0. By downgrading to tensorflow==1.1.0 and tensorflow-transform==0.1.9 as well as updating the reddit query to replace all instances of r'\n+|\x00+' with double backslashes the code was able to run and finish successfully.

**Comment by elmer-garduno** [comment] 2017-06-24 06:18
So should r'\n+|\x00+' be r'\\n+|\\x00+'?

**Comment by dobbysock1002** [comment] 2017-06-24 14:03
I'm not sure whether the intended result was for the raw string literal to make it to BQ or not. 

I think the goal was to remove actual new line and null characters from the body text in which case running directly in BQ: r'\n+|\x00+' or '\n+|\x00+' seem to produce the same result suggesting the raw string literal prefix isn't necessary. Based on [this documentation](https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical) that isn't the result I would expect. I would think without the raw string literal prefix it would search for new line characters/nulls and with it, it would search for the literal \n and \x00.

Submitting the query from the python script is a different story. Python is stripping out the r' and replacing \n and \x00 with an actual new line character and null before submitting the query to bigquery which is resulting in bigquery complaining about an unclosed string literal. 

"Message: Syntax error: Unclosed string literal"

By adding the double backslash I stopped having that issue. With or without the preceding r' seems to make no difference.

This code has existed for a while though, and other people seem to be able to submit it, so perhaps the issue is with my computer/python version?

**Comment by dobbysock1002** [comment] 2017-06-24 14:08
Returning to the original issue that was fixed with different package versions, I think it could be really helpful if the readme for each of the examples listed the actual packages and package versions used to run it successfully when testing it.

**Comment by elmer-garduno** [comment] 2017-06-24 16:58
Thanks a fix for the unescaped character is on the way.

Regarding the versions I expect this sample to work with tf.tranform 0.1.10 I'll update the setup.py file accordingly.

**Comment by elmer-garduno** [comment] 2017-06-26 07:21
The unescaped characters problem has been fixed along with the updated tf.Transform dependency.

**Closed by elmer-garduno** 2017-06-26 07:21 UTC

**Comment by dobbysock1002** [comment] 2017-06-26 17:57
Everything seems to be running now without issue and it's working with tf.transform 0.1.10. Thank you!
