### ISSUE TITLE
No Saved Model after successfully trained the models on ml engine

### ISSUE THREAD

**Issue by ziranfeng** [GoogleCloudPlatform/cloudml-samples#203] opened 2018-06-07 03:41 UTC
For problems running the sample code please provide the following information.

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux (deployed on GCP terminal)
- **TensorFlow version (use command below)**:tensorflow==1.8.0
- **Python version**: Python 2.7.13
- **Exact command to reproduce**: 
#!/bin/bash

echo "Submitting a Cloud ML Engine job..."

REGION="us-central1"
TIER="BASIC" # BASIC | BASIC_GPU | STANDARD_1 | PREMIUM_1
BUCKET="********" # change to your bucket name

MODEL_NAME="housing_regression" # change to your model name

PACKAGE_PATH=trainer # this can be a gcs location to a zipped and uploaded package
TRAIN_FILES=gs://${BUCKET}/path/to/data/train-data-*.csv
VALID_FILES=gs://${BUCKET}/path/to/data/eval-data-*.csv
MODEL_DIR=gs://${BUCKET}/path/to/models/${MODEL_NAME}

CURRENT_DATE=`date + %Y%m%d_%H%M%S`
JOB_NAME=train_${MODEL_NAME}_${TIER}_${CURRENT_DATE}

#JOB_NAME=tune_${MODEL_NAME}_${CURRENT_DATE} # for hyper-parameter tuning jobs

gcloud ml-engine jobs submit training ${JOB_NAME} \
        --job-dir=${MODEL_DIR} \
        --runtime-version=1.4 \
        --region=${REGION} \
        --scale-tier=${TIER} \
        --module-name=trainer.task \
        --package-path=${PACKAGE_PATH}  \
        --config=config.yaml \
        -- \
        --train-files=${TRAIN_FILES} \
	--train-steps=10000 \
        --train-batch-size=200 \
        --eval-files=${VALID_FILES} \
        --eval-batch-size=200 \
        --learning-rate=0.01 \
        --hidden-units="64,32,10" \
        --layer-sizes-scale-factor=0.5 \
        --num-layers=3

- **Tensorflow Transform environment (if applicable, see below)**:

### Describe the problem

Hi, I'm currently practicing GCP using the examples in the repo.
I successfully trained and made predictions locally but when I followed the steps to submit ML jobs on GCP. The training job was completed successfuly but I cannot find "savedmode.pb" (the saved model or etc) in my bucket (MODEL_DIR).
I didn't change any code but just upload the data to bucket and using the above command to submit the job.
Any one has similar problem?

### Source code / logs

The example I used is under
cloudml-samples/cloudml-template/examples/housing-regression/

**Comment by ksalama** [comment] 2018-06-07 11:21
@ziranfeng - Thank you for this. I managed to reproduce the issue and resolve it. Could you please try the following:

- remove the --num-epochs=10 from the command args. The number of epochs can only be useful if you specified the dataset size. Then the training step will be computed. Otherwise, just use the --train-steps argument.

- make sure that you are pointing to the correct locations of the train and eval data files (just double-check the names).

By default, the number of epochs should be None. I will update this in a PR. I will also simplify the example of command to submit a training job.

**Comment by ziranfeng** [comment] 2018-06-07 17:19
@ksalama - Thank you for your help. I removed --num-epochs=10 and submitted job again but I still cannot find the saved_model.pb etc. Please see the below screenshots:

![image](https://user-images.githubusercontent.com/14118209/41115311-1fac29b6-6a55-11e8-8045-f6ad7d8c33c6.png)

![image](https://user-images.githubusercontent.com/14118209/41115336-30d597d6-6a55-11e8-9f74-b3173a43101a.png)

![image](https://user-images.githubusercontent.com/14118209/41115359-42d74736-6a55-11e8-9656-d1f8522bdc58.png)


It seems there was no INFO showing the model was saved.
I'm think if it is because the example has 2 train files and the GCP take the job as tuning rather than generating the model.

Thanks again.

**Comment by ksalama** [comment] 2018-06-07 18:08
@ziranfeng - Ok, you also need to set the default num-epoch value in the task.py to None, since it is using the default value if you don't supply it to the command argument.

**Comment by ziranfeng** [comment] 2018-06-07 18:36
@ksalama -  Hi Ksalama, the problem is solved! Really appreciated!

**Comment by happyhuman** [comment] 2018-06-07 23:12
Looks like there is no more issue here. I am going to go ahead and close this.

**Closed by happyhuman** 2018-06-07 23:12 UTC
