### ISSUE TITLE
I can't get "flowers" to work with inception resnet architecture

### ISSUE THREAD

**Issue by deramos** [GoogleCloudPlatform/cloudml-samples#308] opened 2018-11-14 09:42 UTC
**I can't get flowers example to run using inception resnet**
I ran the "flower" code as it is (inception v3) using a custom dataset, and it worked. Now, I modified the code to use the same custom dataset and inception resnet architecture. It didn't work. I was having an apache beam problem in the preprocessing stage. I am using the following versions

`tensorflow == 1.11.0
apache-beam == 2.8.0
google-cloud-dataflow == 2.5.0`

I packaged the external code which contains the Inception Resnet file and other utility code using 
`python setup.py sdist --formats=gztar`

I followed this link 
https://beam.apache.org/documentation/sdks/python-pipeline-dependencies/#local-or-nonpypi to add extra_package to apache beam pipeline.

Then I ran the preprocess command like this:
`python trainers/inception_resnet/preprocess.py --input_dict "$DICT_FILE" \
--input_path "gs://custom-machine-ml/images/test.csv" \
--output_path "${GCS_PATH}/preproc/eval" --cloud \ 
--extra_package custom-code-0.1.tar.gz` 

But I still get an error `No module named "inception_resnet_v2"`

If I update `google-cloud-dataflow` and `apache-beam[gcp]` by running `pip install --upgrade google-cloud-dataflow apache-beam[gcp]` I get downgraded to `apache-beam==2.5.0`. Yet, the problem still persists. 

I am using python 2.7 and virtualenv

**Comment by davidcavazos** [comment] 2018-11-19 18:49
I believe the problem is that it's using `--extra_package custom-code-0.1.tar.gz` is installing a package named `custom-code`, so `inception_resnet_v2` is still not found. If you have multiple dependencies, as modules in different directories, it might be easier to try the `setup.py` approach. That way it can discover all the packages that live in your working directory and create the egg files for them. The docs point to the [Juliaset](https://github.com/apache/beam/tree/master/sdks/python/apache_beam/examples/complete/juliaset) example for that, but if you find the `setup.py` file to be a bit messy, you can also give [this one a look](https://github.com/GoogleCloudPlatform/cloudml-samples/blob/master/molecules/setup.py).

**Comment by deramos** [comment] 2018-11-21 08:41
@davidcavazos 
Thanks for your reply. However, I don't think that's the case. The tar file is `custom_code-0.1.tar.gz` which installs a package named `custom_code`. Then from my code, I did `from custom_code import inception_resnet_v2`, and I get the error `No module named 'custom_code'`. If I do `pip install custom_code-0.1.tar.gz` on my local computer, the package installs successfully with a package `custom_code` in the `site-packages` folder. 

My set up file is very similar to that of `molecules` project. I will check the setup file of `Juliaset`. 

Thanks a lot

**Comment by gogasca** [comment] 2019-06-28 06:37
Closing issue, as we are deprecating flowers. Re-open if needed.

**Closed by gogasca** 2019-06-28 06:37 UTC
Labels: SAMPLE_REQUEST, help wanted, type: question
