### ISSUE TITLE
tf.Transform and Google DataFlow Templates Integration

### ISSUE THREAD

**Issue by joshreuben456** [GoogleCloudPlatform/cloudml-samples#28] opened 2017-03-22 04:20 UTC
We are in the process of establishing a Machine Learning pipeline on Google Cloud, leveraging GC ML-Engine for distributed TensorFlow training and model serving, and DataFlow for distributed pre-processing jobs.

 We would like to run our Apache Beam apps as DataFlow jobs on Google Cloud. looking at the [ML-Engine samples](https://github.com/GoogleCloudPlatform/cloudml-samples/blob/master/criteo_tft/preprocess.py)
 it appears possible to get **tensorflow_transform.beam.impl AnalyzeAndTransformDataset** to specify which **PipelineRunner** to use as follows:
```python
from tensorflow_transform.beam import impl as tft
pipeline_name = "DirectRunner"
p = beam.Pipeline(pipeline_name) 
p | "xxx" >> xxx | "yyy" >> yyy | tft.AnalyzeAndTransformDataset(...)
``` 

 [TemplatingDataflowPipelineRunner](https://cloud.google.com/dataflow/java-sdk/JavaDoc/com/google/cloud/dataflow/sdk/runners/TemplatingDataflowPipelineRunner) provides the ability to separate our preprocessing development from parameterized operations - see here: https://cloud.google.com/dataflow/docs/templates/overview 

we could leverage this to dynamically generate a  `tf.Transform CsvCoder`

The steps of using DataFlow Templates are as follows:
* A) in **PipelineOptions** derived types, change option types to **ValueProvider<T>** 
* B) change runner to **TemplatingDataflowPipelineRunner** 
* C)  **mvn archetype:generate** to store template in GCS (python way: a yaml file like TF Hypertune ???)
* D) **gcloud beta dataflow jobs run --gcs-location —parameters**

For (A), we could define UserOptions subclassed from `PipelineOptions` and use the `add_value_provider_argument` API to add specific arguments to be parameterized:
```
class UserOptions(PipelineOptions):
     @classmethod
     def _add_argparse_args(cls, parser):
         parser.add_value_provider_argument('--value_provider_arg', default='some_value')
         parser.add_argument('--non_value_provider_arg', default='some_other_value')
```

The question is: Can you show me how we can we use **tf.Transform** to leverage **TemplatingDataflowPipelineRunner** (B & C) ?

Looking at the java [TemplatingDataflowPipelineRunner](https://github.com/GoogleCloudPlatform/DataflowJavaSDK/blob/master/sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/TemplatingDataflowPipelineRunner.java) class , it encapsulates **DataflowPipelineRunner** - How can we create a custom python runner that encapsulates the apache beam python API class [DataflowRunner](https://beam.apache.org/documentation/sdks/pydoc/0.6.0/_modules/apache_beam/runners/dataflow/dataflow_runner.html#DataflowRunner) , that provides the functionality of the java **TemplatingDataflowPipelineRunner**?

**Comment by elmer-garduno** [comment] 2017-03-22 21:38
Thanks @joshreuben456 I'll mark this as a duplicate of https://github.com/tensorflow/transform/issues/6 to followup on single location.

**Closed by elmer-garduno** 2017-03-22 21:38 UTC
